version: "3.8"
services:

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - "8080:8080"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"

  prometheus:
    image: prometheus_spring-boot:latest
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  config-service:
    image: config-service:1.0.0
    ports:
      - "8888:8888"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  eureka-service:
    image: eureka-service:1.0.0
    ports:
      - "7777:7777"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    depends_on:
      - config-service

  gateway-service:
    image: gateway-service:1.0.0
    ports:
      - "9999:9999"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    depends_on:
      - config-service
      - eureka-service

  auth-service:
    image: auth-service:1.0.0
    ports:
      - "6666:6666"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    depends_on:
      - config-service
      - eureka-service
      - keycloak

  crypto-service:
    image: crypto-service:1.0.0
    ports:
      - "8077:8077"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    depends_on:
      - config-service
      - eureka-service

  currency-service:
    image: currency-service:1.0.0
    ports:
      - "8088:8088"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    depends_on:
      - config-service
      - eureka-service

  future-service:
    image: future-service:1.0.0
    ports:
      - "8099:8099"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    depends_on:
      - config-service
      - eureka-service
