global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'Crypto-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.12:8077']
  - job_name: 'Currency-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.12:8088']
  - job_name: 'Future-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.12:8099']
  - job_name: 'Gateway-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.12:9999']